emails = [
    {
        "email_id": "email_001",
        "subject": "Shipping Instruction for BL Verification",
        "from": "customer1@example.com",
        "category": "BL_COMPARISON",
        "status": "OK",
        "review_reason": None,
        "defect_fields": [],
        "has_defect": False,
    },
    {
        "email_id": "email_002",
        "subject": "SI and BL Details Need Verification",
        "from": "customer2@example.com",
        "category": "BL_COMPARISON",
        "status": "MISMATCH",
        "review_reason": None,
        "defect_fields": [
            "gross_weight_kg",
            "port_of_loading"
        ],
        "has_defect": True,
    },
    {
        "email_id": "email_003",
        "subject": "Missing Bill of Lading Attachment",
        "from": "customer3@example.com",
        "category": "BL_COMPARISON",
        "status": "NEEDS_REVIEW",
        "review_reason": "missing_attachment",
        "defect_fields": [],
        "has_defect": False,
    },
    {
        "email_id": "email_004",
        "subject": "New Shipping Instruction Request",
        "from": "customer4@example.com",
        "category": "NEW_SI_REQUEST",
        "status": "OK",
        "review_reason": None,
        "defect_fields": [],
        "has_defect": False,
    },
    {
        "email_id": "email_005",
        "subject": "Invoice Inquiry",
        "from": "customer5@example.com",
        "category": "INVOICE_QUERY",
        "status": "OK",
        "review_reason": None,
        "defect_fields": [],
        "has_defect": False,
    },
    {
        "email_id": "email_006",
        "subject": "General Shipping Inquiry",
        "from": "customer6@example.com",
        "category": "GENERAL",
        "status": "OK",
        "review_reason": None,
        "defect_fields": [],
        "has_defect": False,
    },
    {
        "email_id": "email_007",
        "subject": "Suspicious Shipping Message",
        "from": "unknown@example.com",
        "category": "SPAM",
        "status": "OK",
        "review_reason": None,
        "defect_fields": [],
        "has_defect": False,
    },
]